### ISSUE TITLE
Origin header possibility

### ISSUE THREAD

**Issue by Yentel** [g4klx/DMRGateway#34] opened 2017-08-11 19:58 UTC
Would it be possible to add an "origin header" of some sort to DMRGateway?
This way the DMR networks are able to see if the repeater is connecting directly to that network, or if it's connecting through DMRGateway. :-)

73'

**Comment by oe1kbc** [comment] 2017-08-11 20:09
Why? DMRGateway is only a bridge. I think having nothing to do with origin.

**Comment by cyanide-burnout** [comment] 2017-08-11 20:13
Because it is only bridge and have options to restrict, retumber and reroute traffic.

**Comment by cyanide-burnout** [comment] 2017-08-11 20:22
It looks that Kurt wants to be a secret agent and would not want to describe actual state of it's own repeater. I am sad.

**Comment by oe1kbc** [comment] 2017-08-11 20:27
Why? mine/our repeaters, running with DMRGateway, are clearly described on the DashBoard(s).

**Comment by Yentel** [comment] 2017-08-11 20:34
Because you describe them as being connected to multiple networks.
Not everyone does this, so a header to automatically detect this would be easier :-)

**Comment by g4klx** [comment] 2017-08-11 20:55
Please explain why you need to know? Once identified this information could be used to restrict systems using DMRGateway, or worse. I see no reason to add such identification.

**Comment by cyanide-burnout** [comment] 2017-08-11 21:08
Jonathan, don't think we are crazy and restrictive as other networks, but this change is required to let users know that real configuration of transmitted TGs may be differ from information presented on dashboard. Remember, we provide this info to many systems such as RFinder and then users will claim us. Ok, if you don't want to mark this we can add mark "* configuration could not be trusted" to all MMDVM repeaters. Are you OK with this?

**Comment by dk5ras** [comment] 2017-08-12 07:29
It is not about restricting repetaer sysops, it is the opposite - about repeater sysops restricting or diverting user access. From the transparency view it would be quite useful to have a header, a flag to identify the gateway. Not all sysops handle it that transparent like Kurt from Austria.

**Comment by dg9vh** [comment] 2017-08-12 09:56
Please stop thinking about this. Mark all MMDVMHost systems, because they can be run as Multimode an so it is never been guaranteed that your traffic would be transferred by the repeater.

**Comment by cyanide-burnout** [comment] 2017-08-12 10:33
Dear Kim, first please read carefully and then think about reasons. We are speaking about renumbering and restrictions. Multimode does not restrict or renumber TGs. UX is about this. What are you afraid? If we will need to restrict DMRGateway traffic be sure we know the way. But all we are trying to do is to play open. Why not? What is the reason to decline?

**Comment by dg9vh** [comment] 2017-08-12 11:03
Do be a bit historic: 
I am German... My grandpa lived in NAZI-times... there it was modern to give a star to jewish...
You wish to warn people about using a DMR-Repeater by marking repeater...

more is not to say.

**Comment by cyanide-burnout** [comment] 2017-08-12 11:10
All we are trying to do it to warn users that we have no reliable information about groups and services presented on these repeaters. Again: many users check info at the dashboard website, others check info at RFinder. We provide this information on the data which sysop configured and repeater reported.
In your case this information will be corrupted and users will not trust to dashboard and service. How we can make users trust if repeater sysops lie and cheat? Why are you trying to hide the truth? Due to your grandpa?

**Comment by dg9vh** [comment] 2017-08-12 12:32
The problem is, that you generalize all sysops using DMRGateway to lie and to cheat. You forget, that in real good repeater-sysops talk to their local users and inform them. 

It is not on me to accept such changes - I am still only a user of the system but I use the mechanism of democracy to say what I am thinking without fearing any punishment.

**Comment by dg9vh** [comment] 2017-08-12 12:34
As I said before - if you want to inform the users, tell them, that they should keep in mind that MMDVM always could be a multimode-system and in result of this, DMR and so BrandMeister-Traffic could be skipped for hours if other modes are in use actively.

**Comment by cyanide-burnout** [comment] 2017-08-12 13:05
i see you are not hearing us. There is a big difference between state when channel is busy by other mode and case when repeater doesn't accept call as expected.

**Comment by cyanide-burnout** [comment] 2017-08-12 13:07
One pf your mistake, Kim, is that you are talking only about local users while BM communicates to all user ls the same service level on all repeaters whenever you are. So the idea that if you are from the US you will be able to call your local group in DL. Try to think wide.

**Comment by faxe2110** [comment] 2017-08-13 07:51
Sorry Artem but i can't follow you. First you talking about renumbering and restrictions. OK there maybe i can follow you but this is ONLY for the locale users, all other calls from the netside will arrive on the repeater/MMDVMHost like normal. Then you start to intimidate with your statement "If we will need to restrict DMRGateway traffic be sure we know the way" What is going on?? This problem is JUST on the German side (have not heard something different from other countries) because they started the Germans OM´s who used DMRGateway, and then not all DMRGateways are marked with a star, though they became the Info about it. Take a look in XLX Dashboard and your own. BTW: Have you ever seen that MMDVMHost is disconnecting from the BM Master when it use a another mode?? So even with the MMDVMHost you can’t see it in the DB. So please explain why it should be in DMRGateway and not in MMDVMHost instead and how the users in the US, or somewhere other, should see that the repeater they will reach in Germany or maybe somewhere other in the world is occupied when im not using DMRGateway but just MMDVMHost in Multimode??

**Comment by dg9vh** [comment] 2017-08-13 08:15
Yeah! Emoji-show instead of subject based discussions...

**Comment by cyanide-burnout** [comment] 2017-08-14 13:59
Dear Kim, I ask you to keep out from discussion. I am tried by you. I know you always want to keep last word. 

Now my answer to faxe2110. I told that we want to play to civil game. Just let us know the truth about the way how repeater connected. Some hot heads in this discussion told that we may use this info to block DMRGateway. Then I told that if we want we can break it without knowledge what kind of software. But we don't want to start any war. Why we cannot know the truth on the network side.

**Comment by faxe2110** [comment] 2017-08-16 12:33
Absolut i can follow you. Maybe it´s a bad comparison, but when i come to your Land for holiday with a car, i will be required to read about your traffic rules/law. Same about ham activity, if i come for holiday or may be work, it doesn't matter, i will be better to inform myself how the rules/law and the config of different repeaters will be. In this case i will be better to contact the Sysop, instead of trusting network data. These are not always up to date and "can" also (i do not say that they are) fake. If a network is offer this service, it´s great. But how will the network provider ensure that his data are right?? I think it can´t be able. 
I can´t still not see why the DMRGateway should have this. MMDVMHost Yes maybe  but DMRGateway No can´t see why. Sorry about that. In my world it will be better placed in the MMDVMHost because there we talking about multimode not even one mode.

**Closed** 2017-08-16 12:49 UTC

**Comment by cyanide-burnout** [comment] 2017-08-16 13:11
To faxe2110: it seems like you did not ever use BrandMeister or doen't know about its capabilities.
First, all static TGs are managed via cetral web portal.
And this info always actual. Second, any global TG (ID > 90)  is available on whole network on-demand.
Fill the difference.
